pueblodepelicula/Models/Commercial.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace pueblodepelicula.Models
{
    public class Commercial : Movie
    {
        [MaxLength(60)]
        public string Actor { get; set; }

    }
}

pueblodepelicula/Controllers/CommercialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pueblodepelicula.DAL;
using pueblodepelicula.Filters;
using pueblodepelicula.Models;

namespace pueblodepelicula.Controllers
{
    [UserFilter]
    public class CommercialsController : Controller
    {
        private DBContext db = new DBContext();


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Commercial commercial, HttpPostedFileBase file)
        {
            var fileStream = file.InputStream;
            var binaryReader = new BinaryReader(fileStream);
            var bytes = binaryReader.ReadBytes((Int32)fileStream.Length);
            var base64String = Convert.ToBase64String(bytes, 0, bytes.Length);
            commercial.Photo = base64String;
            if(commercial.RunTime > 360)
            {
                ViewBag.Error = "No se puede crear una pelicula de mas de 360 minutos";
                return View("Error");
            }
            db.Movies.Add(commercial);
            db.SaveChanges();
            return RedirectToAction("Index", "Movies", new { area = "" });
        }

        

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commercial commercial = db.Commercials.Find(id);
            if (commercial == null)
            {
                return HttpNotFound();
            }
            return View(commercial);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Commercial commercial = db.Commercials.Find(id);
            db.Movies.Remove(commercial);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pueblodepelicula/Views/Commercials/Create.cshtml
@model pueblodepelicula.Models.Commercial

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear una pelicula</h2>

@using (Html.BeginForm("Create", "Commercials", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-10">
            Nombre
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            Duración
            @Html.EditorFor(model => model.RunTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RunTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            Sinopsis
            @Html.EditorFor(model => model.Synopsis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Synopsis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            Actor
            @Html.EditorFor(model => model.Actor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Actor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>
            Foto
            <input type="file" name="file" id="file" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver al incio", "Index", "Movies")
</div>

pueblodepelicula/Views/Commercials/Delete.cshtml
@model pueblodepelicula.Models.Commercial

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Commercial</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RunTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RunTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Synopsis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Synopsis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Actor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Actor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Volver al incio", "Index", "Movies")
</div>
    }
</div>