pueblodepelicula/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pueblodepelicula.DAL;
using pueblodepelicula.Filters;
using pueblodepelicula.Models;

namespace pueblodepelicula.Controllers
{
    [UserFilter]
    public class MoviesController : Controller
    {
        private DBContext db = new DBContext();


        public ActionResult Index()
        {
            return View(db.Movies.ToList());
        }


        public ActionResult Type()
        {
            return View();
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var movie = db.Movies.Find(id);
            if (movie is Documentary)
            {
                return RedirectToAction("Details", "Documentaries", new { id });
            }
            else
            {
                return RedirectToAction("Details", "Commercials", new { id });

            }
        }

       

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var movie = db.Movies.Find(id);
            if (movie is Documentary)
            {
                return RedirectToAction("Edit", "Documentaries", new { id });
            }
            else
            {
                return RedirectToAction("Edit", "Commercials", new { id });

            }
        }


        

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            var screenings = db.Screenings.ToList();

            foreach (var item in screenings)
            {
                if (item.MovieID == id)
                {
                    ViewBag.Error = "No se puede eliminar una pelicula que esta en cartelera";
                    return View("Error");
                }
            }
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult LogOut()
        {
            Session.Abandon();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pueblodepelicula/Controllers/ScreeningsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pueblodepelicula.DAL;
using pueblodepelicula.Filters;
using pueblodepelicula.Models;

namespace pueblodepelicula.Controllers
{
    [UserFilter]
    public class ScreeningsController : Controller
    {
        private DBContext db = new DBContext();


        public ActionResult Index()
        {
            var screenings = db.Screenings.Include(s => s.Cinema).Include(s => s.Movie);
            return View(screenings.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Screening screening = db.Screenings.Find(id);
            if (screening == null)
            {
                return HttpNotFound();
            }
            return View(screening);
        }

        public ActionResult Create(int? theatre)
        {
            ViewBag.TheatreID = theatre;
            var cinemas = db.Cinemas.Where(a => a.TheatreID == theatre);
            ViewBag.CinemaID = cinemas.ToList();
            ViewBag.MovieID = new SelectList(db.Movies, "MovieID", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Screening screening)
        {
            var cinema = db.Cinemas.Find(screening.CinemaID);
            screening.Cinema = cinema;
            var theatre = db.Theatres.Find(screening.Cinema.TheatreID);
            screening.Cinema.Theatre = theatre;
            var dateAndTime = DateTime.Now;
            var date = dateAndTime.Date;
            screening.StartTime = date;
            if (db.Movies.Find(screening.MovieID) is Documentary)
            {
                if (db.Cinemas.Find(screening.CinemaID) is HD)
                {
                    ViewBag.Error = "No se puede crear una funcion de un documental en una sala HD";
                    return View("Error");
                }
            }

            var day = screening.StartTime;

            var auxScreenings = db.Screenings.ToList();
            auxScreenings = auxScreenings.Where(f => f.CinemaID == screening.CinemaID).ToList();

            var screenings = new List<Screening>();


            foreach (var a in auxScreenings)
            {
                if (a.StartTime.Date == day)
                {
                    screenings.Add(a);
                }

                if (a.StartTime.Date == day.AddDays(1) && a.StartTime.Hour < 10)
                {
                    screenings.Add(a);
                }
            }

            if (!screenings.Any() || screenings.Last().StartTime.Hour < 10 && screenings.Last().StartTime.Date == screening.StartTime.Date)
            {
                TimeSpan ts = new TimeSpan(10, 0, 0);
                screening.StartTime = screening.StartTime.Date + ts;
            }
            else
            {
                var lastScreening = screenings.Last();
                var startTime = lastScreening.StartTime.AddMinutes(db.Movies.Find(lastScreening.MovieID).RunTime);
                startTime = startTime.AddMinutes(15);

                TimeSpan ts = new TimeSpan(2, 0, 0);
                var maxStartTime = day + ts;
                maxStartTime = maxStartTime.AddDays(1);

                if (startTime < maxStartTime)
                {
                    screening.StartTime = startTime;
                }
                else
                {
                    ViewBag.Error = "Las funciones no pueden iniciar despues de las 02 AM del día siguiente";
                    return View("Error");
                }


            }

            if (ModelState.IsValid)
            {
                db.Screenings.Add(screening);
                db.SaveChanges();
                return RedirectToAction("Index");
            }



            ViewBag.CinemaID = new SelectList(db.Cinemas, "CinemaID", "CinemaID", screening.CinemaID);
            ViewBag.MovieID = new SelectList(db.Movies, "MovieID", "Name", screening.MovieID);
            return View(screening);

        }






        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Screening screening = db.Screenings.Find(id);
           


            if (screening == null)
            {
                return HttpNotFound();
            }
            return View(screening);
        }

        public ActionResult SelectTheatre()
        {
            ViewBag.Theatres = db.Theatres.ToList();
            return View();
        }
        public ActionResult SelectTheatreToDel()
        {
            ViewBag.Theatres = db.Theatres.ToList();
            return View();
        }

        public ActionResult SelectCinema(int? theatreID)
        {
            var cinemas = db.Cinemas.Where(a => a.TheatreID == theatreID);
            ViewBag.Cinemas = cinemas.ToList();
            return View();
        }

 
        public ActionResult VDeleteScreenings(int? cinemaID)
        {
            Session["CinemaID"] = cinemaID;
            var cinema = db.Cinemas.Find(cinemaID);
            var screeningsInCinema = db.Screenings.Where(a => a.CinemaID == cinema.CinemaID).Include(a => a.Movie);
            ViewBag.Screenings = screeningsInCinema.ToList();
            return View();
        }


        public ActionResult DeleteScreenings()
        {
            int cinemaToDel = (int)Session["CinemaID"];
            db.Screenings.RemoveRange(db.Screenings.Where(a => a.CinemaID == cinemaToDel));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Screening screening = db.Screenings.Find(id);
            db.Screenings.Remove(screening);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult LogOut()
        {
            Session.Abandon();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pueblodepelicula/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MovieCity</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/scripts/jquery-3.3.1.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">



    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                


            </div>
            <div>


            </div>
            <div class="navbar-collapse collapse">
                <a href="@Url.Action("Index", "Home")">
                    <img src="/Images/Logo.png" title="MovieCity" height="40" width="40" alt="Logo" />
                </a>
                <ul class="nav navbar-nav">



                    @if (Session["Admin"] == null)
                    {
                        <li>@Html.ActionLink("Login", "GetLogin", "Home", new { @class = "navbar-brand" })</li>
                    }
                    @if (Session["Admin"] != null)
                    {
                        <li>@Html.ActionLink("Funciones", "Index", "Screenings", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Peliculas", "Index", "Movies", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("LogOut", "LogOut", "Home", new { @class = "navbar-brand" })</li>
                    }

                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MovieCity</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>