pueblodepelicula/Models/Documentary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace pueblodepelicula.Models
{
    public class Documentary : Movie
    {
        public Category Category { get; set; }

    }
}

pueblodepelicula/Controllers/DocumentariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pueblodepelicula.DAL;
using pueblodepelicula.Filters;
using pueblodepelicula.Models;

namespace pueblodepelicula.Controllers
{
    [UserFilter]
    public class DocumentariesController : Controller
    {
        private DBContext db = new DBContext();


 


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Documentary documentary, HttpPostedFileBase file)
        {
            var fileStream = file.InputStream;
            var binaryReader = new BinaryReader(fileStream);
            var bytes = binaryReader.ReadBytes((Int32)fileStream.Length);
            var base64String = Convert.ToBase64String(bytes, 0, bytes.Length);
            documentary.Photo = base64String;
            if (documentary.RunTime > 360)
            {
                ViewBag.Error = "No se puede crear una pelicula de mas de 360 minutos";
                return View("Error");
            }
            db.Movies.Add(documentary);
            db.SaveChanges();
            return RedirectToAction("Index", "Movies", new { area = "" });

        }


       

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documentary documentary = db.Documentaries.Find(id);
            if (documentary == null)
            {
                return HttpNotFound();
            }
            return View(documentary);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Documentary documentary = db.Documentaries.Find(id);
            db.Movies.Remove(documentary);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pueblodepelicula/Views/Documentaries/Create.cshtml
@model pueblodepelicula.Models.Documentary

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear una pelicula</h2>

@using (Html.BeginForm("Create", "Documentaries", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-10">
            Pelicula
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            Duración
            @Html.EditorFor(model => model.RunTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RunTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            Sinopsis
            @Html.EditorFor(model => model.Synopsis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Synopsis, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-10">
            Categoria
            @Html.EnumDropDownListFor(model => model.Category, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>
            Foto
            <input type="file" name="file" id="file" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver al inicio", "Index","Movies")
</div>

pueblodepelicula/Views/Documentaries/Delete.cshtml
@model pueblodepelicula.Models.Documentary

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Documentary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RunTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RunTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Synopsis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Synopsis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>